### ISSUE TITLE
semi-colon doesn't register for created cursors

### ISSUE THREAD

**Issue by 7grant2** [magnars/multiple-cursors.el#308] opened 2017-11-04 03:08 UTC
Whenever I type a semi-colon when using multiple cursors, it appears only the original cursor will input the semi-colon. A screenshot includes what I was working on and the instance of this bug.
![screen shot 2017-11-03 at 11 06 30 pm](https://user-images.githubusercontent.com/29149924/32401748-c6af8942-c0eb-11e7-932b-b642bd09ff3e.png)

**Comment by nispio** [comment] 2017-11-04 04:13
For most commands, the first time you invoke the command while in `multiple-cursors-mode` you will be prompted whether you want to run the command for all cursors.  It is likely that you answered no to this question (intentionally or otherwise) at some point.

Run `C-h c ;` to find out the name of the command that is run by inputting `:` (most likely `c-electric-semi&comma`).  Then see if that command is listed in the file `~/.emacs.d/.mc-lists.el`.  If it is, delete that line, save the file, and run `M-x eval-buffer`.

Now the first time you press `;` while in `multiple-cursors-mode` in a C++ buffer, you should see a prompt in the minibuffer asking `Do you want to run c-electric-semi&comma for all cursors? (y or n)`, to which you should respond `y`.

**Comment by nispio** [comment] 2017-11-04 04:18
Closing as duplicate of #287 (among others).  See that issue for a suggestion on how to avoid that prompt for all of the rest of the `c-electric-*` commands.

**Closed by nispio** 2017-11-04 04:18 UTC
