### ISSUE TITLE
trouble with mc/mark-next-* and mc/mark-previous-*

### ISSUE THREAD

**Issue by liefswanson** [magnars/multiple-cursors.el#191] opened 2015-04-02 21:32 UTC
when highlighting an area and using either mc/mark-next-like-this, mc/mark-previous-like-this or any of the similar functions I get strange behavior of it highlighting additional characters to what i highlighted at the next occurrence.

for instance if i have this line
foo bar bar bar foo bar
and i select foo and then mc/mark-next-like-this it will select the next foo, but also the space after it, so i will get the following

	[foo] bar bar bar [foo ]bar

when it should be....

	[foo] bar bar bar [foo] bar
... note the extra space between the third and fourth bar

this problem gets worse when highlighting over several lines, as not only spaces will be highlighted, but whole lines can be caught in the cross fire, or brackets etc. this problem does sometimes also occur when using mc/mark-all-like-this...

an example which litterally just happened was

 	this->destination = [destination];

mc/mark-previous-like-this

	[this->destination] = [destination];

long story short it is greedily highlighting things i did not specify in the process of highlighting matches to the string i wanted. sometimes grabbing whole lines between the first and second highlight. it will select different characters depending on what side of the selection the mark was on, so if it is on the left it will grab more on the left, and vice versa.

additionally when i run mc/mark-next-like-this with nothing selected a mark is placed on the next line as it should be, but one is never left on the line is started on. so If i press it 8 times i will have 8 marks, but no mark on the line i started on.

I have a ton of things from melpa installed, listed them as i imagine there is a possible incompatibility between plugins...

	auto-complete
	csharp-mode
	dash
	d-mode
	ensime
	epl
	ergoemacs-mode
	fic-mode
	fish-mode
	floobits
	flycheck
	fringe-helper
	go-mode
	glsl-mode
	haskell-mode
	icicles
	js2-mode
	less-css-mode
	markdown-mode
	matlab-mode
	minimap
	multiple-cursors
	omnisharp
	pkg-info
	popup
	qml-mode
	s
	scala-mode2
	scss-mode
	smooth-scrolling
	sublime-themes
	tabbar
	tabbar-ruler
	thesaurus
	undo-tree
	web-mode
	writegood-mode
	writeroom-mode
	yasnippet

the version of multiple cursors i have is the one from melpa 20150307.2322
my emacs is 24.4.1
and my distro is arch linux
It may be worth noting that i have two almost identical setups on my laptop and desktop and the problem occurs on both of them.

**Comment by magnars** [comment] 2015-04-02 21:42
The first step here is to bisect that list of packages to find the culprit. Then I can look into why the problem occurs with that package.

**Comment by liefswanson** [comment] 2015-04-02 21:49
phew okay i will let you know after i have eliminated every package systematically

**Comment by liefswanson** [comment] 2015-04-02 21:50
should it be enough to not enable them, or is even requiring them able to create conflict?

**Comment by magnars** [comment] 2015-04-02 21:53
Able, but less likely.

**Comment by liefswanson** [comment] 2015-04-02 22:00
it appears to be ergoemacs-mode. this mode primarily changes around the keybindings from the traditional emacs bindings to ones that dont involve the use of multiple key combos to go through to a single shortcut eg M-x-c becomes M-a. Although i am fairly sure it does some other evil things behind the scenes, as not by any means just full of key remaps. (pretty large package actually).

**Comment by magnars** [comment] 2015-04-02 23:51
Yeah, that one is quite the beast. I'm not sure where to start digging tbqh.

**Comment by liefswanson** [comment] 2015-04-03 01:44
that is okay, i can try and get in contact with them if you like and try and send them in your direction, I am sure someone would have an idea of what could cause that, I am wondering if maybe they are fiddling with how repexps are defined somehow...

**Comment by magnars** [comment] 2015-04-03 08:23
That sounds good.

**Comment by mlf176f2** [comment] 2015-04-03 14:26
I can't reproduce this particular bug.

I do have one incompatability, though.  When I use `mc/edit-lines` I get an additional cursor at the end of my selected lines (if the point is at the end of the line) or an additional cursor at the beginning of my lines (if the point is at the beginning of my line).

**Comment by mlf176f2** [comment] 2015-04-03 14:50
It also removes the line at the beginning of the mark.

**Comment by magnars** [comment] 2015-04-03 15:16
My general impression at this point is that ergoemacs-mode and
multiple-cursors are both too hacky to be compatible.

**Comment by mlf176f2** [comment] 2015-04-03 16:30
It has been working off and on for me for quite some time; I personally like using multiple cursors and sometimes want it back enough to fix the incompatibilities between the two packages.

**Comment by mlf176f2** [comment] 2015-04-03 16:45
I am thinking of writing some multiple-cursors tests, now that Cask supports windows, I may even jump into the Cask bandwagon...

**Comment by mlf176f2** [comment] 2015-04-03 17:35
Nope; Cask still doesn't work for me.

**Comment by mlf176f2** [comment] 2015-04-03 17:42
The editing of lines is the only command that dosen't work for me with ergoemacs-mode enabled, by the way.  The rest work perfectly.

**Comment by liefswanson** [comment] 2015-04-03 23:09
Think I found the issue magnar, https://github.com/ergoemacs/ergoemacs-mode/issues/342#issuecomment-89444052 Though it looks like it is on a very niche case in the ergoemacs side.

**Comment by mlf176f2** [comment] 2015-08-20 16:02
Is there some difference in the way that multiple cursors behave in ert?  Just wondering.  I'm just trying to write tests for the compatibility of these two packages.

**Comment by jtamagnan** [comment] 2016-05-19 20:58
@mattfidler and @liefswanson I was that the issue at https://github.com/ergoemacs/ergoemacs-mode/issues/342 was closed. I don't use ergoemacs but if this is no longer an issue I would like to close this issue as well

**Comment by mattfidler** [comment] 2016-05-20 01:40
It's fine with me

**Closed** 2016-05-20 03:54 UTC
