### ISSUE TITLE
mc/mark-more-like-this-extended ignores left/right

### ISSUE THREAD

**Issue by pronobis** [magnars/multiple-cursors.el#194] opened 2015-04-14 05:41 UTC
It seems that up/down keys work as expected, but left/right do not remove/skip for me. Could you verify it that's a problem in MC or maybe I have some weird conflict?

**Comment by magnars** [comment] 2015-04-14 05:45
It works for me. Just checked. What are the keys bound to when you're in the middle of marking?

**Comment by pronobis** [comment] 2015-04-14 17:14
Thanks, would would be the best way to check that? Anything I tried interrupts the extended mode.

**Comment by magnars** [comment] 2015-04-14 17:56
Ah, I guess you're right - it's implemented as just reading chars off the input stream. Maybe you could call `M-x edebug-defun` on the command in question and see what happens?

**Comment by pronobis** [comment] 2015-04-14 20:06
OK, so it seems that `mc/mmlte--right` is invoked. I followed it down to 
`mc/mark-next-like-this` in which `(mc/mark-lines arg 'forwards)` is run and does not do anything.

**Comment by magnars** [comment] 2015-04-25 07:43
Hmm, that is also weird. Does `mc/mark-next-like-this` also not do anything when used on its own?

**Comment by meta-coder** [comment] 2015-05-05 01:32
@pronobis Are you using ```mc/mark-more-like-this-extended``` command without any region activated?

**Comment by vspinu** [comment] 2015-05-15 13:46
I can confirm this. 

To be more specific, `mc/mark-more-like-this-extended` is not ignoring <left> when there is a selection. It ignores only when you start it with no selection. 

That's because [mc/mark-next-like-this](https://github.com/magnars/multiple-cursors.el/blob/master/mc-mark-more.el#L158-L165) checks for region and as region is not active negative `arg` is passed to `mc/mark-lines` which  ultimately does nothing.

**Comment by vspinu** [comment] 2015-05-15 13:49
Seems that PR #193 fixes that. Any chance it can be merged soon?

**Comment by magnars** [comment] 2015-05-24 09:21
#193 is now merged. Closing this. Reopen if the issue reemerges.

**Closed by magnars** 2015-05-24 09:21 UTC
