### ISSUE TITLE
How mark all like this?

### ISSUE THREAD

**Issue by alexei28** [magnars/multiple-cursors.el#284] opened 2017-04-17 14:57 UTC
Windows 7, Emacs 25.1 , package Helm:

Suppose I has some text:

test: 1111
11111111
test: 2222
22222222
test: 3333
3333333
test: 4444
44444444
test: 5555
5555555

And I want to mark all text **test:**

So my steps are:
1. Select text **test:**
2. Run command "**mc/mark-next-like-this**"  4 TIMES.
3. As result all text  **test:** are marked.

It's work. OK.
But I want to mark all text **test:** ONLY BY ONE COMMAND. Is it possible?

**Comment by nispio** [comment] 2017-04-17 18:00
Not to be too cynical, but did you try reading the manual before asking this question?  `mc/mark-all-like-this` is mentioned many times there.  That is the command you are looking for.

**Comment by alexei28** [comment] 2017-04-18 06:52
> Not to be too cynical, but did you try reading the manual before asking this question? mc/mark-all-like-this is mentioned many times there. That is the command you are looking for.

Without **helm** package command  "**mc/mark-all-like-this**" is  work. But with **helm** package this command NOT work.

**Comment by nispio** [comment] 2017-04-18 14:11
Are you binding `mc/mark-all-like-this` to a key? Or are you invoking it
via `M-x`?  Try binding it to a key, and if you still have problems come
back and post specific steps to reproduce the problems you are seeing.

**Comment by alexei28** [comment] 2017-04-18 17:18
In my keybinging I use this: (as in manual)

_(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)_

BUT, my Emacs work with **CUA mode**. So when use **C-c** the selected text is auto unselect.
So as result  "**C-c C-<**" not work. 
This problem fix by rebinding command **mc/mark-all-like-this** to another keybinding.
E.g. 
_(global-set-key (kbd "C-M-<") 'mc/mark-all-like-this)_

and now by keybinding it's work. 

BUT via M-x not work.

**Comment by nispio** [comment] 2017-04-18 17:53
In general, extended commands (i.e. `M-x`) do not always work well with multiple-cursors and it is recommended to interact with mc via keybindings exclusively.  That said, I am able to successfully run `mc/mark-all-like-this` via `helm-M-x` when starting from `emacs -q`.  I am fairly confident that your issue is because at some point you received the following prompt:

    do helm-M-x for all cursors? (y or n)

To which you responded "y."   You can remedy this situation by finding and removing the line in your `~/.emacs.d/.mc-lists.el` file that says `helm-M-x`, and then restarting emacs.  The next time you activate multiple-cursors via an extended command, you will receive that prompt again, to which you should answer "n" this time.

I am closing this issue, but feel free to come back if fixing to `.mc-lists.el` file does not solve the problem.

**Closed by nispio** 2017-04-18 17:53 UTC
