### ISSUE TITLE
emacs multiple-cursors insert letters (numbers) issue

### ISSUE THREAD

**Issue by eddeyang** [magnars/multiple-cursors.el#268] opened 2016-10-11 16:51 UTC
I've created an ascii video at [https://asciinema.org/a/63b67gx2hm5pasdvjkhiyq4ud][1] to demo my emacs issue with emacs. I created 4 lines of text and created 4 cursors (see 00:36). Then I use `C-a` moved the cursors to the beginning of the lines. After that, I use `mc/insert-letters` to insert letters (see 00:46).  Note that at this time the status line shows `mc:4` means I have 4 cursors.  After I inserted the letters, the status line shows `mc:3` (see 00:49) and the mini buffer is still activated with the command `mc/insert-letters` selected by default. If I press Enter again, the letters `a, b, c` only installed in line 2, 3, 4 and the status line shows `mc:4` again. At the end of the video, I tried the command `mc/insert-numbers` and it shows similar behavior. It seems this behavior is not correct. Could anyone help to confirm please? If it's an issue, how to fix it?

  [1]: https://asciinema.org/a/63b67gx2hm5pasdvjkhiyq4ud

**Comment by nispio** [comment] 2016-10-11 17:24
Unable to reproduce with `emacs -q` using Emacs 25.1 and Multiple Cursors 20160719.216 from melpa. 

In general it is not recommended to interact with multiple cursors via `M-x` and even less so through `smex`.  That said, in this case I still get expected behavior when I follow the steps in your video, with and without `smex`.

**Comment by eddeyang** [comment] 2016-10-11 18:28
I'm not very good at emacs and I don't know how to use Multiple Cursors with it. When I use the `-q` option it seems I can use Multiple Cursors. This is [my .emacs.d](https://github.com/eddeyang/my_emacsd/) and could you help me to take a look whether are there any errors?

**Comment by nispio** [comment] 2016-10-11 20:28
Write the following to a file and save it as ~/init-multiple-cursors.el

    (add-to-list 'load-path (concat user-emacs-directory "elpa/multiple-cursors-20160802.1155"))
    (require 'multiple-cursors)

You may need to modify the version number or path of where your version of multiple-cursors is found.  Now start emacs as follows:

    emacs -Q -l ~/init-multiple-cursors.el

Then see if you get the same unexpected behavior.  If the problem persists, even with `emacs -q` then make sure to post the version of emacs you are using, the operating system, and the version of multiple cursors.

**Comment by eddeyang** [comment] 2016-10-12 01:31
@nispio, Thanks for your suggestion and multiple cursor works well in that case. I've identified the root cause of my problem. It's the `smex` package smex-20151213.609. When I enable it in my init.el file, I always have the behavior described in my video. It's a pretty old version `smex-20151213.609` and I'm using emacs 25.1. Maybe it does not compatible with the new emacs released recently.

**Comment by jtamagnan** [comment] 2016-10-12 02:18
Since smex incompatibility is a known issue I will close this. If you want to do something like this bind it to a hot key maybe

**Closed** 2016-10-12 02:19 UTC
